# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
lune = "lune-org/lune@0.8.3"
rbxcloud = "Sleitnick/rbxcloud@0.10.0"
rojo = "rojo-rbx/rojo@7.4.1"
selene = "Kampfkarren/selene@0.26.1"
stylua = "johnnymorganz/stylua@0.20.0"
tarmac = "rojo-rbx/tarmac@0.7.5"
wally = "UpliftGames/wally@0.3.2"
wally-patch-package = "Barocena/wally-patch-package@1.2.1"
