call_parentheses = "Input"
collapse_simple_statement = "Always"
column_width = 130
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"

[sort_requires]
enabled = false
