[package]
name = "synnwave/jtoh-kit"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "6.0.0"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.1.0"
