name: Deploy

on:
    workflow_dispatch:

jobs:
    build-and-deploy:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ok-nick/setup-aftman@v0.4.2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Build project
          run: lune run build.luau true

        - name: Deploy project
          run: mantle deploy --environment production
          env:
            ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
        
        - name: Push mantle state
          run: |
              git config --global user.name 'synnwave'
              git config --global user.email 'synnwave@users.noreply.github.com'
              git commit -am "Github Actions Mantle State"
              git push