name: Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: lune run build.luau true

      - name: Deploy project
        run: rbxcloud experience publish -a "$API_KEY" -u 5628492917 -p 16315273730 -t published -f kit.rbxl
        env:
          API_KEY: ${{ secrets.OPENCLOUD }}
